# Cloudflare Tunnel configuration
# Replace TUNNEL_ID with your actual tunnel ID after creation

tunnel: HEREIS-ABIGFAT-LYING-FAKETUNNEL
credentials-file: /etc/cloudflared/credentials.json

# Ingress rules to route traffic to Traefik
ingress:
  # Route all traffic from your domain to Traefik
  - hostname: "*.example.com"
    service: http://192.168.101.10:80
  - hostname: "example.com"
    service: http://192.168.101.10:80
  # Catch-all rule to return 404
  - service: http_status:404

# Logging configuration
logDirectory: /var/log/cloudflared
loglevel: info
